name: Deploy React App from GitHub to AWS Elastic Beanstalk
on:
  # activates the workflow when there is a push on the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest # the operating system your job should run on
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Latest Repo
        # checks out your repository under the GitHub workspace so that your workflow can access it
        uses: actions/checkout@v2

      - name: Generate Deployment Package 
        # zip all files except .git
        run: zip -r deploy-sawariya-store-ui-app.zip * -x "**.git**"

      - name: Get timestamp
        uses: gerred/actions/current-time@main
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@main
        id: format-time
        with:
          # replaces '[:\.]+' in the timestamp with '-'
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
         #  input the credentials you used to setup AWS CLI and credentials for the application environment
          aws_access_key: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          application_name: inventory-management-ui
          environment_name: Inventorymanagementui-env
          version_label: "app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-2
          deployment_package: deploy-sawariya-store-ui-app.zip

      - name: Deployed!
        run: echo App deployed to ELB